### ISSUE TITLE
HTTP 502, malformed HTTP version "Status:" -  Caddy says

### ISSUE THREAD

**Issue by norohind** [wxh06/caddy-uwsgi-transport#4]
Greetings.
Caddy returns me `502 Bad Gateway` when I'm trying to query an endpoint that caddy should proxy to an uwsgi server via uwsgi native protocol. I have boiled down the problem to minimal reproducible example: <https://github.com/norohind/caddy-uwsgi-transport>.

So, that how it looks from client side (*-D -* makes curl print out headers to stdout):
```
$ curl -D - http://127.0.0.1:8888
HTTP/1.1 502 Bad Gateway
Server: Caddy
Date: Tue, 28 Nov 2023 19:25:55 GMT
Content-Length: 0
```

At the same time in logs of caddy and uwsgi appear following lines

```
caddy-uwsgi-transport-issue-uwsgi-1  | [pid: 1|app: 0|req: 6/6] 172.22.0.1:57030 () {32 vars in 378 bytes} [Tue Nov 28 19:25:55 2023] GET  => generated 11 bytes in 0 msecs (HTTP/1.1 200) 1 headers in 43 bytes (4 switches on core 0)
caddy-uwsgi-transport-issue-caddy-1  | {"level":"error","ts":1701199555.950834,"logger":"http.log.error","msg":"malformed HTTP version \"Status:\"","request":{"remote_ip":"172.22.0.1","remote_port":"57030","client_ip":"172.22.0.1","proto":"HTTP/1.1","method":"GET","host":"127.0.0.1:8888","uri":"/","headers":{"User-Agent":["curl/8.4.0"],"Accept":["*/*"]}},"duration":0.001092797,"status":502,"err_id":"verjzexi7","err_trace":"reverseproxy.statusError (reverseproxy.go:1265)"}
```

As it can be seen, uwsgi receives the query and appears to respond, but caddy, for some reason, can't handle the response and thus returns to http query 502 code.

Most interesting part is this problem occurs only if uwsgi is run with config file (uwsgi.conf in the example). If you would
run uwsgi with cli args then everything works fine. Conveniently, in the example, I left an option to run uwsgi with the same parameters as in uwsgi.conf but as cli args (Details in *Steps to reproduce*).

# Steps to reproduce

```shell
git clone https://github.com/norohind/caddy-uwsgi-transport.git
cd caddy-uwsgi-transport
docker-compose up  # This one shall build images and then run containers, logs going to be on stdout

# Now in separate shell query the uwsgi app through caddy
curl -D - http://127.0.0.1:8888  

```

## Mystery with "equivalence" of cli args and config file

In docker-compose.yaml: Comment in line 22 and comment out line 21, then make `docker-compose up --build`.
Then query caddy again using curl and you should get 200 http response, although options provided to uwsgi in both cases seems to be identical.

# Versions
- caddy-uwsgi-transport: I believe it builds from the latest commit, as for now it is `573bdc411df6d73ea72730cd755324bbb3a0151b`
- Uwsgi (from logs): uWSGI 2.0.23 (64bit)
- `Caddy -v`: v2.7.5 h1:HoysvZkLcN2xJExEepaFHK92Qgs7xAiCFydN5x5Hs6Q=
- `docker version`: 
```
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.3
 Git commit:        tag v24.0.7
 Built:             Wed Nov  1 19:52:11 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.3
  Git commit:       tag v24.0.7
  Built:            Wed Nov  1 19:52:11 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.8
  GitCommit:        UNSET
 runc:
  Version:          1.1.9
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
  ```
- `docker-compose -v`: `Docker Compose version v2.21.0`

**Comment by wxh06** [comment]
Thank you. This is the most detailed reproduction I've ever seen.

I've reproduced the issue successfully and believe this is caused by the absence of the HTTP *start-line* in the response of uWSGI.
Currently, this transport forward the uwsgi (protocol) text response directly to Caddy without modification (even though it's an invalid HTTP response). Caddy ended up with a 502 status code as it is not able to parse the response header.

For the sake of brevity, I've changed `socket` to `http-socket` to perform the HTTP request in text instead of binary:

```diff
-socket = :3000
+http-socket = :3000
```

<details>
<summary>uwsgi.ini</summary>

```ini
[uwsgi]
http-socket = :3000
wsgi-file = foobar.py
```
</details>

Raw request:

```http
GET / HTTP/1.1
```

Raw response header:

```http
Status: 200 OK
Content-Type: text/html
```

while a valid `HTTP/1.1` response header should be:

```http
HTTP/1.1 200 OK
Content-Type: text/html
```

cURL's behavior:

```sh
$ curl http://127.0.0.1:3031
curl: (1) Received HTTP/0.9 when not allowed
```

**Comment by wxh06** [comment]
According to [The uwsgi Protocol](https://uwsgi-docs.readthedocs.io/en/latest/Protocol.html) in uWSGI document:

> Every uwsgi request generates a response in the uwsgi format.

However, 83 (`S` in `Status: 200 OK`) is not a valid value of `modifier1` mentioned in the [document](https://uwsgi-docs.readthedocs.io/en/latest/Protocol.html#packet-descriptions).
Thus, the uWSGI server response is neither valid HTTP nor in the uwsgi format.

**Comment by norohind** [comment]
Thanks for your reply, it pointed me to the solution.
Flag `-c` doesn't mean `--config` and even doesn't mean config in general, quote from help page:
`-c|--cgi-mode                         force CGI-mode for plugins supporting it`

So, if I remove `-c` and runs it as `uwsgi /uwsgi.ini` it works fine. It's a miracle it has worked with cgi-mode enabled with nginx for years.

Reference: https://github.com/unbit/uwsgi/issues/707
My minimal reproducible example with applied fix (`-c` argument removed): https://github.com/norohind/caddy-uwsgi-transport/tree/solution

Thanks for your time and consideration, the problem, as it is often happens, was lying in RTFM area, lol. Guess now I will enjoy the plugin.

**Comment by wxh06** [comment]
Congrats on finding the solution!
I did not realize that `-c` stands for CGI instead of Config either.
