### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by Justman100** [wxh06/caddy-uwsgi-transport#8]
uWSGI command:
```
uwsgi --ini /home/weblate.ini
```

weblate.ini
```
[uwsgi]
http = :3314
chdir = /home/Weblate/weblate
wsgi-file = /home/Weblate/weblate/wsgi.py
callable = application
processes = 4
threads = 2
master = true
```

My Caddyfile
```
:9090 {
	reverse_proxy 127.0.0.1:3314 {
		transport uwsgi
	}
}
```

**Comment by wxh06** [comment]
Could you please provide the full log/error message from Caddy's output?

**Comment by Justman100** [comment]
> Could you please provide the full log/error message from Caddy's output?

> http.log.error  unexpected EOF  {"request": {"remote_ip": "<myip>", "remote_port": "59179", "client_ip": "2a02:2454:849f:aa00:1101:c207:cf93:1c41", "proto": "HTTP/3.0", "method": "GET", "host": "<mySite>", "uri": "/favicon.ico", "headers": {"Priority": ["u=6"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"], "Referer": ["https://<mySite>/"], "Sec-Fetch-Mode": ["no-cors"], "Accept": ["image/avif,image/webp,*/*"], "Accept-Language": ["de,en-US;q=0.7,en;q=0.3"], "Accept-Encoding": ["gzip, deflate, br"], "Sec-Fetch-Dest": ["image"], "Sec-Fetch-Site": ["same-origin"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h3", "server_name": "<mySite>"}}, "duration": 60.060753162, "status": 502, "err_id": "fc2gppj5c", "err_trace": "reverseproxy.statusError (reverseproxy.go:1267)"}

**Comment by wxh06** [comment]
It seems that the upstream server (uWSGI) closed the connection unexpectedly after 60 seconds.

**Comment by wxh06** [comment]
According to your configuration, you are not using *the uwsgi protocol* but *HTTP* instead:

```properties
[uwsgi]
http = :3314
```

You have two options:

1. Use HTTP
   You do not need this plugin. Just remove `transport uwsgi` from Caddyfile.
2. Use uwsgi
   Replace `http = :3314` with `socket = :3314` in your `weblate.ini`.
